In [42]:
pip install numpy pandas

Note: you may need to restart the kernel to use updated packages.


In [43]:
import numpy as np

In [44]:
A=[1, 2, 3, 4, 5]
A

[1, 2, 3, 4, 5]

In [45]:
B= np.array([1, 2, 3, 4, 5]) #nos permite hacer más dimensiones
type(B)

numpy.ndarray

In [46]:
import sys

#size of array
size_array= sys.getsizeof(1) *len(A)
print("Size Array A: ", size_array)

Size Array A:  140


In [47]:
size_numpy=B.itemsize * B.size
print("Size numpy: ", size_numpy)

Size numpy:  20


In [48]:
A=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
A.shape

(2, 5)

In [50]:
A.flatten() #Lista de una dimensión

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
A.flatten().shape

(10,)

In [52]:
A.reshape(5,2) #Al revés de shape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [53]:
A.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [54]:
A.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [55]:
A.reshape(5,-1,1).shape

(5, 2, 1)

In [56]:
B = np.arange(0,100)
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [57]:
B.shape

(100,)

In [58]:
B.reshape(4,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [59]:
zeros = np.zeros([10,2])
zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
ones=np.ones([10,1])
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [61]:
A=[1,2,3]
A * 2 #concatena

[1, 2, 3, 1, 2, 3]

In [62]:
A=np.array([1,2,3])
A * 2

array([2, 4, 6])

In [63]:
B=np.array([4,5,6])
A+B

array([5, 7, 9])

In [64]:
print(A,B)

[1 2 3] [4 5 6]


In [65]:
A*B

array([ 4, 10, 18])

In [66]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [67]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
print(A)

[1 2 3]


In [69]:
np.mean(A)

2.0

In [70]:
np.median(A)

2.0

In [71]:
A=np.array([1,2,0,4,5,6])
C=np.where(A>2)
C


(array([3, 4, 5], dtype=int64),)

# Dot product

In [82]:
def dot_product(a, b):
    result = 0
    for i in range(len(a)):
        result= result + a[i]*b[i]
    return result

In [83]:
a = np.random.rand(10000) #vectores de 100 elementos aleatorios
b = np.random.rand(10000)
print(dot_product(a,b))

2500.0731610284665


In [84]:
import time

start=time.time()

total = time.time() -start
print(dot_product(a,b))

total = time.time()- start
print("total time ", total)

2500.0731610284665
total time  0.008695125579833984


In [85]:
import time

start=time.time()

#dot product with numpy
dot_product = np.dot(a,b)

total = time.time()- start
print("total time ", total)

total time  0.0
